### ISSUE TITLE
No such file or directory: 'bvlc-alexnet.npy'

### ISSUE THREAD

**Issue by waveroarer** [udacity/alexnet-feature-extraction#15]
I am using anaconda.

After I type "python imagenet_inference.py"

Traceback (most recent call last):
  File "imagenet_inference.py", line 7, in <module>
    from alexnet import AlexNet
  File "C:\Users\An\Documents\CarND-Alexnet-Feature-Extraction\alexnet.py", line
 4, in <module>
    net_data = np.load("bvlc-alexnet.npy", encoding="latin1").item()
  File "C:\Users\An\Miniconda3\lib\site-packages\numpy\lib\npyio.py", line 370,
in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'bvlc-alexnet.npy'

**Comment by waveroarer** [comment]
I got it. Thanks.

**Comment by subshall** [comment]
I meet the same problem。how do you solve it？？？

**Comment by aseelam** [comment]
Download the weights and training data into your CarND-Alexnet-Feature-Extraction folder.
