### ISSUE TITLE
'ellipsis' object has no attribute 'get_shape'

### ISSUE THREAD

**Issue by AloshkaD** [udacity/alexnet-feature-extraction#6]
I've tried to run traffic_sign_inference.py but I've got this error which is generated from Alexnet.py
`
Traceback (most recent call last):
  File "traffic_sign_inference.py", line 18, in <module>
    probs = AlexNet(resized)
  File "/home/ros/SDC/CarND-Alexnet-Feature-Extraction/alexnet.py", line 39, in AlexNet
    conv1_in = conv(features, conv1W, conv1b, k_h, k_w, c_o, s_h, s_w, padding="SAME", group=1)
  File "/home/ros/SDC/CarND-Alexnet-Feature-Extraction/alexnet.py", line 11, in conv
    c_i = input.get_shape()[-1]
AttributeError: 'ellipsis' object has no attribute 'get_shape'

`

**Comment by AloshkaD** [comment]
I've got it. I had an old version of TF.
